CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,7 +59,22 @@ jobs:
 
     - name: Validate current action
       run: |
-        echo "${{fromJSON(steps.current.outputs.result).fullName}}"
+        if [ "${{fromJSON(steps.current.outputs.result).owner.isUser}}" != "" ]; then
+          echo "::error Repository owner isUser does't equal to an empty string"
+          exit 1
+        fi
+        if [ "${{fromJSON(steps.current.outputs.result).owner.isOrganisation}}" != "true" ]; then
+          echo "::error Repository owner isOrganisation does't equal to true"
+          exit 1
+        fi
+        if [ "${{fromJSON(steps.current.outputs.result).fullName}}" != "${{github.repository}}" ]; then
+          echo "::error Repository full name '${{fromJSON(steps.current.outputs.result).fullName}}' doesn't equal to expected '${{github.repository}}'"
+          exit 1
+        fi
+        if [ "${{fromJSON(steps.current.outputs.result).owner.login}}" != "${{github.repository_owner}}" ]; then
+          echo "::error Repository owner '${{fromJSON(steps.current.owner.login).fullName}}' doesn't equal to expected '${{github.repository_owner}}'"
+          exit 1
+        fi
 
 
     - name: Push back
