CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,18 +65,23 @@ jobs:
       env:
         FULL_NAME: ${{fromJSON(steps.current.outputs.result).fullName}}
         OWNER: ${{fromJSON(steps.current.outputs.result).owner.login}}
+        OWNER_IS_USER: ${{fromJSON(steps.current.outputs.result).owner.isUser}}
         OWNER_IS_ORGANISATION: ${{fromJSON(steps.current.outputs.result).owner.isOrganisation}}
       run: |
         if [ "$FULL_NAME" != "${{github.repository}}" ]; then
           echo "::error Repository full name '$FULL_NAME' doesn't equal to expected '${{github.repository}}'"
           exit 1
         fi
-        if [ "$OWNER_IS_ORGANISATION" != "true" ]; then
-          echo "::error Repository owner isOrganisation does't equal to true"
-          exit 1
-        fi
         if [ "$OWNER" != "${{github.repository_owner}}" ]; then
           echo "::error Repository owner '$OWNER' doesn't equal to expected '${{github.repository_owner}}'"
+          exit 1
+        fi
+        if [ "$OWNER_IS_USER" != "" ]; then
+          echo "::error Repository owner isUser is not empty"
+          exit 1
+        fi
+        if [ "$OWNER_IS_ORGANISATION" != "true" ]; then
+          echo "::error Repository owner isOrganisation does't equal to true"
           exit 1
         fi
 
